"""Read or change JBrowser's version number in one place.

The version lives in ``jbrowser/__init__.py`` (``__version__``). Everything else is derived
from it: the Windows file properties of JBrowser.exe (``tools/version_info.txt``), the
installer's name and version, the git tag of a release and the auto-updater's comparison.

Usage::

    python tools/version.py                 # print the current version
    python tools/version.py --sync          # regenerate tools/version_info.txt from it
    python tools/version.py --set 1.4.1     # change the version everywhere (then commit)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INIT = ROOT / "jbrowser" / "__init__.py"
VERSION_INFO = ROOT / "tools" / "version_info.txt"
VERSION_RE = re.compile(r'^__version__\s*=\s*"(\d+)\.(\d+)\.(\d+)"', re.MULTILINE)

VERSION_INFO_TEMPLATE = """\
# Windows file properties of JBrowser.exe (PyInstaller --version-file).
# GENERATED by tools/version.py from jbrowser/__init__.py: do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, 0),
    prodvers=({a}, {b}, {c}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'The JBrowser Company'),
        StringStruct('FileDescription', 'JBrowser - welcome to the internet, again'),
        StringStruct('FileVersion', '{v}'),
        StringStruct('InternalName', 'JBrowser'),
        StringStruct('LegalCopyright', '\\u00a9 2026 The JBrowser Company. GNU GPL v3.'),
        StringStruct('OriginalFilename', 'JBrowser.exe'),
        StringStruct('ProductName', 'JBrowser'),
        StringStruct('ProductVersion', '{v}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version() -> str:
    m = VERSION_RE.search(INIT.read_text(encoding="utf-8"))
    if not m:
        raise SystemExit(f"Could not find __version__ in {INIT}")
    return ".".join(m.groups())


def write_version_info(version: str) -> None:
    a, b, c = version.split(".")
    VERSION_INFO.write_text(VERSION_INFO_TEMPLATE.format(a=a, b=b, c=c, v=version), encoding="utf-8")


def set_version(version: str) -> None:
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit("Versions look like 1.4.1 (major.minor.patch)")
    text = INIT.read_text(encoding="utf-8")
    INIT.write_text(VERSION_RE.sub(f'__version__ = "{version}"', text, count=1), encoding="utf-8")
    write_version_info(version)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--set", metavar="X.Y.Z", help="change the version number")
    p.add_argument("--sync", action="store_true", help="regenerate tools/version_info.txt")
    a = p.parse_args()
    if a.set:
        set_version(a.set)
        print(f"Version set to {a.set}. Add a section for it to CHANGELOG.md, then commit.")
    elif a.sync:
        write_version_info(read_version())
        print(f"tools/version_info.txt now says {read_version()}")
    else:
        print(read_version())
    return 0


if __name__ == "__main__":
    sys.exit(main())
